USE sakila;
-- List the number of films per category.--

select c.name,count(*) from category c
inner join film_category fc
ON c.category_id=fc.category_id
group by c.name
order by count(*) desc;

-- Retrieve the store ID, city, and country for each store.
select store_id,c.city, country 
from store s 
inner join address a
on s.address_id=a.address_id
inner join city c
on a.address_id=c.city_id
inner join country con
on c.country_id=con.country_id;

-- Calculate the total revenue generated by each store in dollars.
select sto.store_id, sum(p.amount) from store sto
	inner join customer cu
		on sto.store_id = cu.store_id
    inner join payment p
		on cu.customer_id = p.customer_id
group by sto.store_id
;

-- Determine the average running time of films for each category.

select c.name, avg(f.length) from film f 
	inner join film_category fc
		on f.film_id = fc.film_id
	inner join category c on fc.category_id = c.category_id
group by c.name;
